# noise test
model: gpt-3.5-turbo-0125 #  gemini-pro or mixtral or  llama-2-70b
dataset:  symbolic # math and symbolic and commonsense 
start_num: 0
test_num: 300
batch_size: 5

# subtask
## math
math:
  subtask: base-11

## symbolic
symbolic:
  subtask: equal # equal or longer

# method
method: basemodel # CD-CoT or basemodel,  smoothllm, selfdenoise, selfpolish, contrastivecot, ISC, SCO, BT

## basemodel, smoothllm, selfdenoise, selfpolish, contrastivecot, ISC
temperature_reason: 1
n_reason: 5

## CD-CoT
use_logged_rephrased_result: False  # for ablation, default to False
use_logged_ICL_result: False  # for ablation, default to False
n_rephrase: 5
temperature_rephrase: 1
topp_rephrase: 1
use_clean_shot: True  # for ablation, default to True
c_reason: [3,2]  # [5] or [3,2] or [2,2,1] or [1,1,1,1,1]
temp_reason: 1
topp_reason: 1

# use_processed_dataset or use raw dataset
use_processed_dataset: True

# use subfolder_suffix
# subfolder_suffix_path: 4_shot_ablation

## when use_processed_dataset is True
processed_dataset_options:
  ## processed dataset path or one of ["default-zeroshot"， "default-clean", "default-(irrelevant|inaccurate)-(easy|medium|hard)-(fixed|random)"]
  processed_dataset_path: default-clean
  n_shots: 3
  using_subset: False

# when use_processed_datset is False
raw_dataset_options:
  ## in-context 
  if_in_context: True
  n_shots: 0 # clean shot num
  ## noise
  if_noise: True
  n_noisy_shots: 10
  noise_type: inaccurate # irrelevant or inaccurate
  noise_ratio: 0.8 # 0.3, 0.5 or 0.8
  noise_distribution: fixed #fixed or random

# ICL format
prefix_context: True ## prefix

# model
## gpt
gpt:
  api: openai  # openai
